# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix-development: "chore(deps-dev): docker"
    open-pull-requests-limit: 10 # Limit number of open PRs
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "docker-compose" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix-development: "chore(deps-dev): docker-compose"
    open-pull-requests-limit: 10 # Limit number of open PRs
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix-development: "chore(deps-dev): GHA"
    open-pull-requests-limit: 10 # Limit number of open PRs
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix-development: "chore(deps-dev): maven"
    open-pull-requests-limit: 10 # Limit number of open PRs
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
