version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tenpo-challenge-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/tenpo_challenge
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    networks:
      - tenpo-network

  postgres:
    image: postgres:16-alpine
    container_name: tenpo-challenge-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=tenpo_challenge
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - tenpo-network

  redis:
    image: redis:7-alpine
    container_name: tenpo-challenge-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - tenpo-network

networks:
  tenpo-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data: